Fix _repr_html_ method of SDFGState for correct Jupyter notebook rendering (#2085)
**Description**

The SDFGState representation in Jupyter notebooks raises a `TypeError`.
This happens because the ` _repr_html_(self)` method creates a temporary
SDFG for rendering, but assigns the `_arrays` property as a regular
dictionary instead of the required `dace.sdfg.NestedDict`. This type
mismatch causes the error.

**Fix**

The issue is fixed by changing this line in the SDFGState's `
_repr_html_(self)` method:
```python
sdfg._arrays = {k: self.sdfg.arrays[k] for k in arrays}
```
to
```python
sdfg._arrays = dace.sdfg.NestedDict({k: self.sdfg.arrays[k] for k in arrays})
```
This ensures the temporary SDFG’s `arrays` property has the correct
type, resolving the error.

The updated method then looks like this:
```python
    def _repr_html_(self):
        """ HTML representation of a state, used mainly for Jupyter
            notebooks. """
        # Create dummy SDFG with this state as the only one
        from dace.sdfg import SDFG
        arrays = set(n.data for n in self.data_nodes())
        sdfg = SDFG(self.label)
        sdfg._arrays = dace.sdfg.NestedDict({k: self.sdfg.arrays[k] for k in arrays})
        sdfg.add_node(self)

        return sdfg._repr_html_()
```

**How to reproduce the bug**

In a Jupyter notebook, add this cells:
1. Get any example SDFG: 
    ```python
    import dace
    
    @dace.program
    def vectorCopy(A: dace.float64[128], B: dace.float64[128]):
        for i in dace.map[0:128]:
            B[i] = A[i]
            
    
    sdfg = vectorCopy.to_sdfg()
    sdfg
    ```
2. Retrieve the (only) `SDFGState` and display it:
    ```python
    states = sdfg.states()
    states[0]
    ```
    This raises the error:
    ```python
TypeError: Invalid type "dict" for property _arrays: expected NestedDict
    ```

**Credits**
I discovered the bug and presented it during a meeting with my
supervisor, Yakup Koray Budanaz, who quickly provided the one-line fix.